### PR TITLE
Change version of Node.js runtime to node20

### PR DESCRIPTION
**Pull request by maikelvdh**

### CODE REVIEW

**Comment by bcomnes** [comment]
Thanks this is overdue.

**Comment by maikelvdh** [comment]
You're welcome @bcomnes will you merge this change in?

**Comment by bcomnes** [comment]
Sorry, for the delay, I just needed to confirm dist matched my local output before merging. Looks like it does so thank you for that! Release incoming.

**Comment by bcomnes** [comment]
Ok give `bcomnes/netrc-creds@v3` a whirl.

**Pull request merged**
